# Generated by Django 5.1.2 on 2024-10-18 13:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usersrelation_delete_relation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersRelation',
            new_name='UserRelation',
        ),
    ]
